services:
  api:
    build:
      context: .
      dockerfile: deployments/docker/api/Dockerfile
    command: go run ./cmd/api/
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8080:8080"
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: deployments/docker/worker/Dockerfile
    command: go run ./cmd/worker/
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8080:8080"
    restart: unless-stopped
